config/routes.rb
Woodhack::Application.routes.draw do
  
  get "authentication/create"

  get "elo/images"

  get "battles/skateparks" => "elo#locations"
  get "battles/top-skateparks" =>"elo#top_locations"
  post "elo/vote"

  # get "locations/index"
  
  namespace :admin do
    resources :users
    resources :roles
    resources :images
    get "locations" => "locations#index"
    post "locations/multi_update" => "locations#multi_update"
  end
  
  get "admin/index"
  # get "admin/users"
  # post "admin/users/update"
  get "admin/location_stats" => "admin#locations"
  get "admin/duplicates"
  # get "admin/parkskaters"
  # get "admin/skateparkcom"
  get "admin/marker_verification"
  # get "admin/google_static_maps"

  get "iphone/feed"
  get "iphone/your_images"
  get "iphone/news"
  get "iphone/about"
  get "iphone/help"

  match 'search' => 'search#index'

  
  namespace :api do
    namespace :v1 do
      resources :locations do
        collection do
          get 'countries'
          get 'states'
          get 'cities'
          get 'search'
        end
      end
      resources :ratings
      resources :images
      get "authentication/login"
      post "authentication/login"
      post "authentication/create"
      get "authentication/exists"
    end
    namespace :v2 do
      resources :locations, :only => [:index, :show, :update, :create]
      post "authentication/create"
    end
  end
  
  resources :locations do
    resources :comments
    member do
      post 'verify_marker'
      post 'rate'
      get 'revert'
    end
  end
  
  get "places", :to => "places#index"
  get "places/*id", :to => "places#index"
  
  get "support", :to => "welcome#support"
  get "terms_of_service", :to => "welcome#terms_of_service"
  
  
  # auth
  match '/auth/:provider/callback' => 'authentications#create'  
  devise_for :users#, :controllers => {:registrations => 'registrations'}, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  resources :authentications
  
  
  require 'sidekiq/web'
  # constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  # constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  # end
  
  # root :to => "places#index"
  # root :to => "elo#locations"
  root :to => "welcome#index"
  
  
end

app/views/admin/duplicates.html.erb
<% content_for :title do %>
Duplicates
<% end %>

<div class="container">
  <header>
    <h1><%= @duplicates.flatten.uniq.count %> Possible Duplicates</h1>
    <p>
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="span12">
      <% @duplicates.each do |set| %>
      <h4><%= link_to "#{set.first.lat}, #{set.first.lng}", locations_path(:lat => set.first.lat.to_s, :lng => set.first.lng.to_s), :target => "_blank"  %></h4>
      <ul>
        <% set.each do |location| %>
          <li><%= link_to location.name, location %> <%= location.distance_to(set.first) %> </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<h1>Admin</h1>

app/views/admin/landing_page_generator.html.erb
<h1>landing_page_generator</h1>

<%= debug @response.results.facets %>

app/views/admin/locations.html.erb
<h1>Locations</h1>
<p>
  Locations with ratings <strong><%= (@locations_with_ratings * 100.0 / @locations_total).round(2) %>%</strong> 
  <%= @locations_with_ratings %> / <%= @locations_total %>
</p>

<p>
  Locations that have images <strong><%= (@locations_with_images * 100.0 / @locations_total).round(2) %>%</strong>
  <%= @locations_with_images %> / <%= @locations_total %>
</p>

<p>
  Locations with descriptions <strong><%= (@locations_with_descriptions * 100.0 / @locations_total).round(2) %>%</strong>
  <%= @locations_with_descriptions %> / <%= @locations_total %>
</p>

<p>
  Verified Locations <strong><%= (@locations_verified * 100.0 / @locations_total).round(2) %>%</strong>
  <%= @locations_verified %> / <%= @locations_total %>
</p>

<h2>Count by US State</h2>
<ul>
  <% @count_by_state.sort {|x,y| y["count(state)"] <=> x["count(state)"]}.each do |i| %>
    <li>
      <%= i["state"] %>
      <ul>
        <li>Total: <%= i["count(state)"] %></li>
        <li>Verified : <%= @count_verified_by_state.detect { |j| j["state"] == i["state"] }.try(:[], "count(state)") || 0 %></li>
      </ul>
      
      
    </li>
  <% end %>
</ul>

<h2>Count by Country</h2>
<ul>
  <% @count_by_country.sort {|x,y| y["count(country)"] <=> x["count(country)"]}.each do |i| %>
    <li><%= i["country"] %> <%= i["count(country)"] %></li>
  <% end %>
</ul>

app/views/admin/marker_verification.html.erb
<% content_for :title do %>
Marker Verification
<% end %>

<div class="container">
  <header>
    <h1>Marker Verification</h1>
    <p>
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="span12">
      <ol>
      <% @locations.each_with_index do |location, index| %>
        <li>
          <%= link_to location.name, location %><br>
          <%= l JSON.parse(@recent_marker_votes[index])['verified_at'].to_datetime %><br>
          YES: <%= location.marker_yes %>,
          NO: <%= location.marker_no %><br>
          <%= location.marker_contributors.collect { |i| "#{JSON.parse(i)['user']}-#{JSON.parse(i)['vote']}" }.join(", ") %>
        </li>
      <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/admin/skateparkcom.html.erb
<style type="text/css" media="screen">
  #admin_map {width:100%;height:450px;position:fixed;left:0;top:0px}
  .container.main-content {margin-top:450px}
</style>

<h1>Skatepark.com</h1>

<ol id="parklist">
<% $redis.keys("anemone:pages:http://skatepark.com/skateparks/*").each do |key| %>
  <% lat =  $redis.hget(key, "lat") %>
  <% lng =  $redis.hget(key, "lng") %>
  <% if lat and lng %>
    <li data-lat="<%= lat %>" data-lng="<%= lng %>">
      <%= key %><br>
      <%= lat %>,
      <%= lng %>
    </li>
  <% end %>
<% end %>
</ol>

app/views/admin/users.html.erb
<h1>Users</h1>
<ol>
  <% @users.each do |user| %>
    <li data-update-url="<%=  %>">
      <%= user.email %><br>
      roles: <%= user.roles.join(", ") %>
    </li>
  <% end %>
</ol>
<%= will_paginate @users %>
<%= form_tag "/admin/users/update", :method => "get" do  %>
  <%= text_field_tag "id", @users.first.id, :method => "post" %>
  <ul>
    <li>
      <%= check_box_tag "user[role_ids][]", "photoadmin" %> photo admin
    </li>
    <li>
    <%= check_box_tag "user[role_ids][]", "photo" %>
    photo
    </li>
    <%= submit_tag "Updaate" %>
  </ul>
<% end %>
<script type="text/template" id="form-template">
  
</script>