config/routes.rb
Woodhack::Application.routes.draw do
  
  get "authentication/create"

  get "elo/images"

  get "battles/skateparks" => "elo#locations"
  get "battles/top-skateparks" =>"elo#top_locations"
  post "elo/vote"

  # get "locations/index"
  
  namespace :admin do
    resources :users
    resources :roles
    resources :images
    get "locations" => "locations#index"
    post "locations/multi_update" => "locations#multi_update"
  end
  
  get "admin/index"
  # get "admin/users"
  # post "admin/users/update"
  get "admin/location_stats" => "admin#locations"
  get "admin/duplicates"
  # get "admin/parkskaters"
  # get "admin/skateparkcom"
  get "admin/marker_verification"
  # get "admin/google_static_maps"

  get "iphone/feed"
  get "iphone/your_images"
  get "iphone/news"
  get "iphone/about"
  get "iphone/help"

  match 'search' => 'search#index'

  
  namespace :api do
    namespace :v1 do
      resources :locations do
        collection do
          get 'countries'
          get 'states'
          get 'cities'
          get 'search'
        end
      end
      resources :ratings
      resources :images
      get "authentication/login"
      post "authentication/login"
      post "authentication/create"
      get "authentication/exists"
    end
    namespace :v2 do
      resources :locations, :only => [:index, :show, :update, :create]
      post "authentication/create"
    end
  end
  
  resources :locations do
    resources :comments
    member do
      post 'verify_marker'
      post 'rate'
      get 'revert'
    end
  end
  
  get "places", :to => "places#index"
  get "places/*id", :to => "places#index"
  
  get "support", :to => "welcome#support"
  get "terms_of_service", :to => "welcome#terms_of_service"
  
  
  # auth
  match '/auth/:provider/callback' => 'authentications#create'  
  devise_for :users#, :controllers => {:registrations => 'registrations'}, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  resources :authentications
  
  
  require 'sidekiq/web'
  # constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  # constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  # end
  
  # root :to => "places#index"
  # root :to => "elo#locations"
  root :to => "welcome#index"
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @top_parks     = Location.verified.order("elo_rank DESC").where("elo_rank > 1200").limit(4)
    @recent        = Location.verified.order("updated_at DESC").limit(4)
    @recent_images = Image.approved.limit(24)
    
    @tire = Tire::Search::Search.new(Location.index_name)
    @tire.facet :states, :global => true do |search|
      search.terms :state, :size => 51
      search.facet_filter :term, { :country => "United States" }
    end
    @usa = @tire.results.facets['states']['terms'].sort_by { |h| h["term"] }
  end
  
  def support
  end
  
  def terms_of_service
  end
end

app/views/welcome/index.html.erb
<% content_for :title do %>
Skatepark Locator App
<% end %>
<% content_for :head do %>
<meta property="og:type"        content="pushwood:skate_park" />
<meta property="og:url"         content="<%= root_url %>" /> 
<meta property="og:title"       content="Pushwood Skate Parks" /> 
<meta property="og:description" content="" /> 
<meta property="og:image"       content="" />
<% end %>
<div class="container">
  <header>
    <h1>Welcome to Pushwood Skate Park Locator</h1><p>
    Pushwood is your database of skateparks!  Our service is just about the facts. 
    All of our data is curated by our administrators, so you can be sure that the information you get is accurate.
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="row">
      <div class="span8">
        <div id="myCarousel" class="carousel slide">
          <!-- Carousel items -->
          <div class="carousel-inner">
            <% @top_parks.each_with_index do |location, i| %>
            <div class="<%= "active " if i == 0 %>item">
              <%= image_tag "http://maps.google.com/maps/api/staticmap?center=#{location.lat},#{location.lng}&zoom=20&size=640x350&scale=2&maptype=hybrid&sensor=false" %>
              <div class="carousel-caption">
                <h4><%= link_to location.name, location %></h4>
                <p>
                  <%= truncate location.description, length: 140 %>
                </p>
              </div>
            </div>
            <% end %>
          </div>
          <!-- Carousel nav -->
          <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
        </div>
        
        <section>
          
          <h2>Add to Pushwood.com</h2>
          <p>Pushwood.com is community powered! See something we are missing or do you have updates for your local skate park? You can add it and our staff will approve it.</p>
    
          <% if current_user %>
            <%= link_to 'Add a Skate Park', new_location_path, class: "btn btn-inverse" %>
          <% else %>
            <%= link_to 'Add a Skate Park', "/auth/facebook", class: "btn btn-inverse" %>
          <% end %>
    
          <h2>Recently Added or Updated Skate Parks</h2>
          <div class="row">
            <% @recent.each do |location| %>
              <div class="span2">
                <%= link_to image_tag(location.google_staticmap), location %>
                <h5><%= location.name %></h5>
              </div>
            <% end %>
          </div>
    
          <h2>Top Skate Parks</h2>
          <p>Skate Park popularity is calculated in the <%= link_to "skate park battle", battles_skateparks_path %>.
          <%= link_to "See All Top Parks", "/battles/top-skateparks", class: "" %></p>
          <div class="row">
            <% @top_parks.each do |location| %>
              <div class="span2">
                <%= link_to image_tag(location.google_staticmap), location %>
                <h5><%= location.name %></h5>
              </div>
            <% end %>
          </div>
          
          <h2>United States</h2>
          <div class="row place-list">
            <% @usa.each_slice(11).each do |states| %>
              <div class="span2"><ul><% states.each do |state| %>
                <li><%= link_to state['term'], "/places/united-states/#{state['term'].parameterize}" %> <span class="muted"><%= state['count'] %></span></li>
              <% end %></ul></div>
            <% end %>
          </div>
          
          
          <% @tire.results.facets['states']['terms'].each_with_index do |term,index| %>
            <% next if index > 5 %>
            <h2><%= term['term'] %> <small><%= link_to "see all", "/places/united-states/#{term['term'].downcase}", class: "muted" %></small></h2>
            
            <div class="row">
              <% Location.verified.order(:elo_rank).limit(4).where("state = ?", term["term"]).each do |location| %>
              <div class="span2">
                <%= link_to image_tag(location.google_staticmap), location %>
                <h5><%= location.name %></h5>
              </div>
              <% end %>
            </div>
          <% end %>
          
        </section>
      </div>
      <div class="span4">
        <%= render 'layouts/ad_300x250' %>
        
        <h2>New Photos</h2>
        <p>Photos are uploaded from pushwood.com or our free iPhone App in the available on the Apple Store.</p>
        <% @recent_images.each do |image| %>
          <div class="pull-left home-image">
            <%= link_to image_tag(image.img.url(:iosSmall)), image.location, title: image.location.name %>
          </div>
        <% end %>
        
        <div>
          <script type="text/javascript"><!--
          google_ad_client = "ca-pub-6987587183408883";
          /* Detail Page */
          google_ad_slot = "7547026732";
          google_ad_width = 300;
          google_ad_height = 250;
          //-->
          </script>
          <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
        </div>
      </div>
    </div>
  
  </div>
</div>

app/views/welcome/support.html.erb
<% content_for :title do %>
Skatepark Locator App
<% end %>
<% content_for :head do %>
<meta property="og:type"        content="pushwood:skate_park" />
<meta property="og:url"         content="<%= root_url %>" /> 
<meta property="og:title"       content="Pushwood Skate Parks" /> 
<meta property="og:description" content="" /> 
<meta property="og:image"       content="" />
<% end %>
<div class="container">
  <header>
    <h1>Support</h1>
    <p>
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="span12">
      <p>Need help? Contact help@pushwood.com</p>
    </div>
  </div>
</div>

app/views/welcome/terms_of_service.html.erb
<% content_for :title do %>
Skatepark Locator App
<% end %>
<% content_for :head do %>
<meta property="og:type"        content="pushwood:skate_park" />
<meta property="og:url"         content="<%= root_url %>" /> 
<meta property="og:title"       content="Pushwood Skate Parks" /> 
<meta property="og:description" content="" /> 
<meta property="og:image"       content="" />
<% end %>
<div class="container">
  <header>
    <h1>Terms of Use</h1>
    <p>
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="span12">
      <p>These Terms of Use shall apply to all websites owned and/or operated by the Pushwood, including without limitation the website on which these Terms of Use are posted and Pushwood’s parents, subsidiary and/or affiliate entities whether or not referred to directly as Pushwood. Pushwood maintains this and other websites as a service to its customers. By accessing and/or using the web sites owned, operated and/or maintained by Pushwood, you are expressly agreeing to comply with and be bound by the following Terms of Use and Pushwood’s Privacy Policy separately provided, as well as all applicable laws and regulations. IF YOU DO NOT AGREE WITH THESE TERMS OF USE, YOU ARE NOT AUTHORIZED TO USE THE PUSHWOOD SITES AND MUST NOT ACCESS OR USE THEM. Pushwood may revise and update these Terms of Use at any time; please periodically review them, because your continued usage of the Pushwood Sites indicates your agreement with any such changes.
      </p>

      <p>You further understand and agree that any updates, enhancements or added features of any Pushwood Sites or services shall be made part of these Terms of Use. Additionally, certain of the Pushwood's Sites may be subject to registration, processing and handling fees and/or subject to additional terms of use. You are responsible for promptly paying those fees to insure your right to access the associated Pushwood Sites and/or services.</p>

      <h4>Copyright.</h4>
      <p>Ownership. All content included on the Pushwood Sites, such as text, graphics, logos, button icons, images, audio clips and software, as well as the compilation of any of the foregoing (meaning the collection, arrangement and assembly), are the property of Pushwood or its content suppliers and protected by U.S. and international copyright laws. You acknowledge and agree that Content contained in sponsor advertisements or information presented to you through the Pushwood Sites or by advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by Pushwood or such advertisers, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Pushwood Sites, services, products or software, in whole or in part.</p>
    </div>
  </div>
</div>