config/routes.rb
Woodhack::Application.routes.draw do
  
  get "authentication/create"

  get "elo/images"

  get "battles/skateparks" => "elo#locations"
  get "battles/top-skateparks" =>"elo#top_locations"
  post "elo/vote"

  # get "locations/index"
  
  namespace :admin do
    resources :users
    resources :roles
    resources :images
    get "locations" => "locations#index"
    post "locations/multi_update" => "locations#multi_update"
  end
  
  get "admin/index"
  # get "admin/users"
  # post "admin/users/update"
  get "admin/location_stats" => "admin#locations"
  get "admin/duplicates"
  # get "admin/parkskaters"
  # get "admin/skateparkcom"
  get "admin/marker_verification"
  # get "admin/google_static_maps"

  get "iphone/feed"
  get "iphone/your_images"
  get "iphone/news"
  get "iphone/about"
  get "iphone/help"

  match 'search' => 'search#index'

  
  namespace :api do
    namespace :v1 do
      resources :locations do
        collection do
          get 'countries'
          get 'states'
          get 'cities'
          get 'search'
        end
      end
      resources :ratings
      resources :images
      get "authentication/login"
      post "authentication/login"
      post "authentication/create"
      get "authentication/exists"
    end
    namespace :v2 do
      resources :locations, :only => [:index, :show, :update, :create]
      post "authentication/create"
    end
  end
  
  resources :locations do
    resources :comments
    member do
      post 'verify_marker'
      post 'rate'
      get 'revert'
    end
  end
  
  get "places", :to => "places#index"
  get "places/*id", :to => "places#index"
  
  get "support", :to => "welcome#support"
  get "terms_of_service", :to => "welcome#terms_of_service"
  
  
  # auth
  match '/auth/:provider/callback' => 'authentications#create'  
  devise_for :users#, :controllers => {:registrations => 'registrations'}, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  resources :authentications
  
  
  require 'sidekiq/web'
  # constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  # constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  # end
  
  # root :to => "places#index"
  # root :to => "elo#locations"
  root :to => "welcome#index"
  
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  scope :assignable_roles, where("name = 'photo' OR name = 'photoadmin' OR name = 'admin'")  
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < BaseController
  
    def index
      @roles = Role.all

      respond_to do |format|
        format.html # index.html.erb
      end
    end

    def show
      @role = Role.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
      end
    end

    def new
      @role = Role.new

      respond_to do |format|
        format.html # new.html.erb
      end
    end

    def edit
      @role = Role.find(params[:id])
    end

    def create
      @role = Role.new(params[:role])

      respond_to do |format|
        if @role.save
          format.html { redirect_to [:admin, @role], notice: 'Role was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end

    def update
      @role = Role.find(params[:id])

      respond_to do |format|
        if @role.update_attributes(params[:role])
          format.html { redirect_to [:admin, @role], notice: 'Role was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end

    def destroy
      @role = Role.find(params[:id])
      @role.destroy

      respond_to do |format|
        format.html { redirect_to admin_roles_path }
      end
    end
  end
  
end

app/views/admin/roles/_form.html.erb
<div class="section frm">
  <%= form_for([:admin,   @role]) do |f| %>
    <% if @role.errors.any? %>
      <div id="error_explanation" class="section error">
        <h2><%= pluralize(@role.errors.count, "error") %> prohibited this admin_role from being saved:</h2>

        <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <fieldset>
    <div class="form-row">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="form-row submit">
      <%= f.submit :class => "btn green float-right" %>
    </div>
    </fieldset>
  <% end %>
</div>

app/views/admin/roles/edit.html.erb
<h1>Editing admin_role</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @role] %> |
<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/index.html.erb
<div class="container">
  <header>
    <h1>User Roles</h1>
    <p class="lead">
    </p>
  </header>
</div>

<div class="pageit container">
  <div id="content" class="container">
    <div class="span12">
      <h3>All Roles</h3>
      <table id="users-table" class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @roles.each do |role| %>
          <tr>
            <td><%= role.name %></td>
            <td class="col-actions"><div><%= link_to 'Show List of Users', [:admin, role] %></div><div><%= link_to 'Edit', edit_admin_role_path(role) %></div><div><%= link_to 'Destroy', [:admin, role], confirm: 'Are you sure?', method: :delete %></div></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<h1>Create a New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/show.html.erb
<h1>Role: <span class="bold"><%= @role.name %></span></h1>
<div class="section tbl">
  <h3>Users currently assigned the role of "<%= @role.name %>"</h3>
  <table>
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </thead>
    <tbody>
      <% @role.users.each do |user| %>
      <tr>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Edit User's Roles", edit_admin_user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="section">
  <%= link_to 'Back', admin_roles_path %>
</div>